#!/usr/bin/env bash
# Compare the full Hadron images built for this PR against the published
# ":main" baseline and emit a Markdown size report to stdout.
#
# Used by the "image-size-report" job in PR_amd64.yml so reviewers can see how
# much a change (e.g. adding a new dependency) grows the shipped images.
#
# Usage: image-size-report.sh <pr-sha> <repo-slug>
#   <pr-sha>    git SHA the PR images were tagged with (github.sha)
#   <repo-slug> owner/name used for the ghcr baseline (github.repository)
#
# Sizes are uncompressed image sizes (docker image inspect .Size). The
# per-directory breakdown comes from `du` inside each rootfs. amd64 only.
set -euo pipefail

SHA="${1:?usage: image-size-report.sh <pr-sha> <repo-slug>}"
REPO="${2:?usage: image-size-report.sh <pr-sha> <repo-slug>}"

# name | PR image (this build, pushed to ttl.sh) | main baseline (ghcr.io)
# PR bios tags carry a -amd64 suffix; trusted tags do not (see PR_amd64.yml).
VARIANTS=(
  "hadron-cloud|ttl.sh/hadron-cloud-amd64:${SHA}|ghcr.io/${REPO}-cloud:main"
  "hadron|ttl.sh/hadron-amd64:${SHA}|ghcr.io/${REPO}:main"
  "hadron-cloud-trusted|ttl.sh/hadron-cloud-trusted:${SHA}|ghcr.io/${REPO}-cloud-trusted:main"
  "hadron-trusted|ttl.sh/hadron-trusted:${SHA}|ghcr.io/${REPO}-trusted:main"
)

# Human-readable IEC size; strips a leading "-" so callers control the sign.
human() { numfmt --to=iec --suffix=B "${1#-}"; }

# Top-level rootfs usage of an image: lines of "<bytes>\t<path>", sorted by
# path so join(1) can pair two images. Returns nothing if the image has no
# usable shell (the size table still works without this).
rootfs_du() {
  docker run --rm --entrypoint sh "$1" -c \
    'du -xb --max-depth=1 / 2>/dev/null' 2>/dev/null | sort -k2 || true
}

summary_rows=""
details=""

for v in "${VARIANTS[@]}"; do
  IFS='|' read -r name pr_img main_img <<<"$v"

  # Baseline may legitimately not exist yet (brand new image variant).
  if ! docker pull -q "$main_img" >/dev/null 2>&1; then
    summary_rows+="| \`${name}\` | _not on main yet_ | — | — |"$'\n'
    continue
  fi
  docker pull -q "$pr_img" >/dev/null

  main_sz=$(docker image inspect "$main_img" --format '{{.Size}}')
  pr_sz=$(docker image inspect "$pr_img" --format '{{.Size}}')
  delta=$((pr_sz - main_sz))
  pct=$(awk -v d="$delta" -v m="$main_sz" 'BEGIN{printf "%+.2f", (m>0)?(d/m*100):0}')
  sgn='+'; [ "$delta" -lt 0 ] && sgn='-'
  summary_rows+="| \`${name}\` | $(human "$main_sz") | $(human "$pr_sz") | ${sgn}$(human "$delta") (${pct}%) |"$'\n'

  # Per-directory delta (only dirs whose size actually changed).
  dir_diff=$(join -j2 -a1 -a2 -e0 -o '0,1.1,2.1' \
      <(rootfs_du "$main_img") <(rootfs_du "$pr_img") \
    | awk '$1!="/"{d=$3-$2; if (d!=0) printf "%s\t%d\t%d\t%d\n",$1,$2,$3,d}' \
    | sort -t$'\t' -k4 -nr || true)
  if [ -n "$dir_diff" ]; then
    block="<details><summary><code>${name}</code>: per-directory changes</summary>"$'\n\n'
    block+="| dir | \`main\` | PR | Δ |"$'\n'"|---|--:|--:|--:|"$'\n'
    while IFS=$'\t' read -r dir m p d; do
      [ -z "$dir" ] && continue
      s='+'; [ "$d" -lt 0 ] && s='-'
      block+="| \`${dir}\` | $(human "$m") | $(human "$p") | ${s}$(human "$d") |"$'\n'
    done <<<"$dir_diff"
    block+=$'\n'"</details>"$'\n\n'
    details+="$block"
  fi
done

printf '## 📦 Image size report — PR vs `main` (amd64)\n\n'
printf '| Image | `main` | PR | Δ |\n|---|--:|--:|--:|\n'
printf '%s\n' "$summary_rows"
printf '%b' "$details"
printf '<sub>Uncompressed image sizes (`docker image inspect .Size`). Baseline = current `:main`. Generated by `.github/scripts/image-size-report.sh`.</sub>\n'
