set -ex

(
    echo "# Automatically generated by ca-certificates-$CA_CERTIFICATES_VERSION"
    echo "# $(date -ud@$SOURCE_DATE_EPOCH)"
    echo "#"
    cd /ca-certificates/usr/share/ca-certificates
    find . -name '*.crt' | sort | cut -b3-
) > /ca-certificates/etc/ca-certificates.conf

# generate the bundle in similar way as update-ca-certificates would do
find -- /ca-certificates/usr/share/ca-certificates -name '*.crt' | sort | while read -r i; do
    cat "$i"
    printf "\n"
done > /ca-certificates/etc/ssl/certs/ca-certificates.crt


cat > /ca-certificates/etc/ca-certificates/update.d/certhash <<-EOF
#!/bin/sh
exec /usr/bin/c_rehash /etc/ssl/certs
EOF
chmod +x /ca-certificates/etc/ca-certificates/update.d/certhash

mkdir -p /ca-certificates/etc/ssl/certs
mv /ca-certificates/etc/ssl/certs/ca-certificates.crt \
    /ca-certificates/etc/ssl/certs/
ln -s certs/ca-certificates.crt \
    /ca-certificates/etc/ssl/cert.pem

# Symlinks for OpenSSL 1.1 compatibility
mkdir -p /ca-certificates/etc/ssl1.1/
ln -s /etc/ssl/certs /ca-certificates/etc/ssl1.1/
ln -s /etc/ssl/cert.pem /ca-certificates/etc/ssl1.1/

mkdir -p /ca-certificates/etc/pki/tls/certs

ln -s /etc/ssl/certs/ca-certificates.crt /ca-certificates/etc/pki/tls/certs/ca-bundle.crt