set -ex

(
    echo "# Automatically generated by ca-certificates-$CA_CERTIFICATES_VERSION"
    echo "# $(date -ud@$SOURCE_DATE_EPOCH)"
    echo "#"
    cd /ca-certificates/usr/share/ca-certificates
    find . -name '*.crt' | sort | cut -b3-
) > /ca-certificates/etc/ca-certificates.conf

# generate the bundle in similar way as update-ca-certificates would do
find -- /ca-certificates/usr/share/ca-certificates -name '*.crt' | sort | while read -r i; do
    cat "$i"
    printf "\n"
done > /ca-certificates/etc/ssl/certs/ca-certificates.crt


# Use `openssl rehash` instead of c_rehash: c_rehash is a perl script, and
# openssl rehash is a builtin in the modern OpenSSL we ship everywhere. This
# drops the perl runtime dependency from update-ca-certificates.
cat > /ca-certificates/etc/ca-certificates/update.d/certhash <<-EOF
#!/bin/sh
exec /usr/bin/openssl rehash /etc/ssl/certs
EOF
chmod +x /ca-certificates/etc/ca-certificates/update.d/certhash

mkdir -p /ca-certificates/etc/ssl/certs
mv /ca-certificates/etc/ssl/certs/ca-certificates.crt \
    /ca-certificates/etc/ssl/certs/
ln -s certs/ca-certificates.crt \
    /ca-certificates/etc/ssl/cert.pem

# Symlinks for OpenSSL 1.1 compatibility
mkdir -p /ca-certificates/etc/ssl1.1/
ln -s /etc/ssl/certs /ca-certificates/etc/ssl1.1/
ln -s /etc/ssl/cert.pem /ca-certificates/etc/ssl1.1/

mkdir -p /ca-certificates/etc/pki/tls/certs

ln -s /etc/ssl/certs/ca-certificates.crt /ca-certificates/etc/pki/tls/certs/ca-bundle.crt

# Verify `openssl rehash` works at build time (same command the runtime
# certhash hook runs). The bundle is the only file here so it is skipped (no
# hash symlinks created); this just fails the build fast if openssl rehash
# errors. Real hash symlinks get created at runtime when individual CA files
# are dropped into /etc/ssl/certs.
/usr/bin/openssl rehash /ca-certificates/etc/ssl/certs